---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  tasks:
          - name: Instalando wget
            yum:
                    name: wget
          - name: Instalando unzip
            yum:
                    name: unzip

          - name: Dowload Python
            get_url:
                    url: https://bootstrap.pypa.io/get-pip.py
                    remote_src: yes
                    dest: /tmp
                    mode: 0440

          - name: execute install script
            command: "python /tmp/get-pip.py"

            remote_src: yes
          - name: Extract consul
            unarchive:
                    src:  https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
                    remote_src: yes
                    dest: /usr/bin
          - name: Creates directory
            file:
                    path: /etc/consul.d
                    state: directory
                    recurse: yes
          - name: Creates directory
            file:
                    path: /etc/consul/data
                    state: directory
                    recurse: yes
